### ISSUE TITLE
 Response status code does not indicate success: 402 (Payment Required).

### ISSUE THREAD

**Issue by TW527E** [JDDKCN/NyanKoLauncher#1]
![Screenshot_2024-12-12_19-19-17](https://github.com/user-attachments/assets/04f9c3dd-2c7c-4e3f-961a-eb8cb81ca9c5)
😭

**Comment by JDDKCN** [comment]
中国境外国家注册deepseek是不送token的，是不是没充钱喵www
可以充个几块钱再试试

**Comment by TW527E** [comment]
「中國境外國家」😂
好的（沒錢🫠）
